name: Deploy services to heroku.

on:
  workflow_run:
    workflows: ["App health-check"]
    types: [completed]
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Publish and Deploy Backend.
        uses: gonuit/heroku-docker-deploy@v1.3.2 
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME_API }}
          dockerfile_directory: ./api
          dockerfile_name: API.PROD.Dockerfile
          docker_options: "--no-cache"
          process_type: web
      - name: Build, Publish and Deploy Frontend.
        uses: gonuit/heroku-docker-deploy@v1.3.2 
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME_API_FRONTEND }}
          dockerfile_directory: ./client
          dockerfile_name: PROD.Dockerfile
          docker_options: "--no-cache"
          process_type: web